language: ruby
rvm:
- 2.3.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - COMMIT_AUTHOR_EMAIL: mcanina@gmail.com
  - ENCRYPTION_LABEL: 3b1e7d965353
sudo: required
cache:
  yarn: true
before_install:
  - openssl aes-256-cbc -K $encrypted_3b1e7d965353_key -iv $encrypted_3b1e7d965353_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - node --version
before_script:
  - make build
  - make check
script:
  - bash ./deploy.sh

